# Generated by Django 3.2.8 on 2021-11-24 07:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
